//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grap
        {
            get
            {
                return SteamVR_Actions.default_Grap;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cue
        {
            get
            {
                return SteamVR_Actions.default_Cue;
            }
        }
        
        public virtual SteamVR_Action_Boolean Forword
        {
            get
            {
                return SteamVR_Actions.default_Forword;
            }
        }
        
        public virtual SteamVR_Action_Boolean Backword
        {
            get
            {
                return SteamVR_Actions.default_Backword;
            }
        }
        
        public virtual SteamVR_Action_Boolean Left
        {
            get
            {
                return SteamVR_Actions.default_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Right
        {
            get
            {
                return SteamVR_Actions.default_Right;
            }
        }
        
        public virtual SteamVR_Action_Vector2 moving
        {
            get
            {
                return SteamVR_Actions.default_moving;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchPad
        {
            get
            {
                return SteamVR_Actions.default_TouchPad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPos
        {
            get
            {
                return SteamVR_Actions.default_TouchPos;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
